name: pet_food_accessories_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  rive: ^0.13.20
  iconsax_flutter: ^1.0.0
  badges: ^3.1.2
  like_button: ^2.0.5
  provider:
  google_maps_flutter: 2.10.0
  custom_info_window: ^1.0.1
  image_picker: ^1.1.2
  scratcher: ^2.5.0
  panara_dialogs: ^0.1.5
  device_preview: ^1.2.0
  slide_to_act: ^2.0.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  toastification: ^3.0.2
  lottie: ^3.3.1

dependency_overrides:
  google_maps_flutter_ios: 2.13.1
  google_maps_flutter_web: ^0.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
