name: pet_food_accessories_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  ## --- Flutter SDK & UI --- ##
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  iconsax_flutter: ^1.0.0
  badges: ^3.1.2
  like_button: ^2.0.5
  shimmer: ^3.0.0
  lottie: ^3.3.1
  rive: ^0.13.20
  slide_to_act: ^2.0.2

  ## --- Image & Media --- ##
  cached_network_image: ^3.4.1
  image_picker: ^1.1.2

  ## --- Carousel & Animations --- ##
  carousel_slider: ^5.0.0
  scratcher: ^2.5.0

  ## --- Maps & Location --- ##
  google_maps_flutter: 2.10.0
  custom_info_window: ^1.0.1

  ## --- Dialogs & Toasts --- ##
  panara_dialogs: ^0.1.5
  toastification: ^3.0.2

  ## --- State Management --- ##
  provider:

  ## --- Firebase --- ##
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5

  ## --- HTTP & Networking --- ##
  http: ^1.3.0

  ## --- Utilities & Dev Tools --- ##
  device_preview: ^1.2.0

dependency_overrides:
  google_maps_flutter_ios: 2.13.1
  google_maps_flutter_web: ^0.5.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
