// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgPcbEwnTm8YXrkJqU4i4dhoJCkYTLZ98',
    appId: '1:922429960602:web:81a2382cc1c47d97500a23',
    messagingSenderId: '922429960602',
    projectId: 'pawmart-32ea2',
    authDomain: 'pawmart-32ea2.firebaseapp.com',
    storageBucket: 'pawmart-32ea2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYrtBJj8msP1LaIucwDr6ScOkh4dLnvBY',
    appId: '1:922429960602:android:1bac32f0004fa393500a23',
    messagingSenderId: '922429960602',
    projectId: 'pawmart-32ea2',
    storageBucket: 'pawmart-32ea2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyBAKYwiByV3Ah1Ke97PR2haKfXYaYqzg',
    appId: '1:922429960602:ios:fe546c56b7d98a84500a23',
    messagingSenderId: '922429960602',
    projectId: 'pawmart-32ea2',
    storageBucket: 'pawmart-32ea2.firebasestorage.app',
    iosBundleId: 'com.example.petFoodAccessoriesApp',
  );
}
